grpc:
  port: 6569
spring:
  application:
    name: ticket-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/ticket_api"
    username: postgres
    password: "root"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false