grpc:
  port: 6568
spring:
  application:
    name: moviesession-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/moviesession_api"
    username: root
    password: "root"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true